name: tab_overview
description: >
  A widget that enables smooth tab transitions with a grid view of 
  thumbnails for easy tab management and navigation.
version: 0.0.2
homepage: https://github.com/igorkurilenko/tab_overview

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animated_reorderable: ^1.4.2
  hero_here: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
